//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class card
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public card()
    {
        this.deck_has_card = new HashSet<deck_has_card>();
    }

    public int idCard { get; set; }
    public string CardName { get; set; }
    public string CardSet { get; set; }
    public string CardType { get; set; }
    public string CardRarity { get; set; }
    public Nullable<int> CardCost { get; set; }
    public Nullable<int> CardAttack { get; set; }
    public Nullable<int> CardHealth { get; set; }
    public string CardText { get; set; }
    public string CardPlayerClass { get; set; }
    public string CardImg { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<deck_has_card> deck_has_card { get; set; }
}

public partial class deck
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public deck()
    {
        this.deck_has_card = new HashSet<deck_has_card>();
    }

    public int idDeck { get; set; }
    public string DeckName { get; set; }
    public int User_idUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<deck_has_card> deck_has_card { get; set; }
    public virtual user user { get; set; }
}

public partial class deck_has_card
{
    public int Deck_idDeck { get; set; }
    public int Card_idCard { get; set; }
    public int CardCount { get; set; }

    public virtual card card { get; set; }
    public virtual deck deck { get; set; }
}

public partial class user
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public user()
    {
        this.deck = new HashSet<deck>();
    }

    public int idUser { get; set; }
    public string UserName { get; set; }
    public string UserPassword { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<deck> deck { get; set; }
}
